site_name: MVS B2B Dev Docs
site_url: https://mvsb2b.example.com

theme:
  name: material
  palette:
    - scheme: light
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - def_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji

nav:
  - Home: index.md
  - Front-End Guides:
    - E-Commerce:
      - Project Information: front-end/project-info.md
      - Setup & Install: front-end/front-end-setup.md
      - Troubleshooting: front-end/front-end-troubleshooting.md
      - Guides & How-Tos:
        - Adding localized text: front-end/guides/adding-updating-text.md
        - Adding new API spec: front-end/guides/new-spec-guide.md
        - MUI Basics: front-end/guides/mui-basics.md
        - Additional Resources: front-end/additional-resources.md
    - WordPress Site:
      - Project Information: front-end/project-info.md # Seth, Createa file for this
  - VM Setup: 
    - Toolkit Setup: vm-setup/toolkit-setup.md
    - VM / Toolkit Troubleshooting: vm-setup/toolkit-trouble-shoot.md
  - Git Guide: git-guide.md


extra_css:
  - stylesheets/custom-colors.css

copyright: MVS Developer Notes
extra:
  generator: false