site_name: Developer Documents
site_url: https://mvsb2b.example.com

theme:
  name: material
  logo: img/midwest_text_white.png
  favicon: img/new-favicon.ico
  palette:
    - scheme: light
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - def_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji

nav:
  - Home: index.md
  - Front-End Guides:
    - E-Commerce (React/NextJS Platform):
      - Project Information: front-end/project-info.md
      - Setup & Install: front-end/front-end-setup.md
      - Troubleshooting: front-end/front-end-troubleshooting.md
      - Guides & How-Tos:
        - Adding localized text: front-end/guides/adding-updating-text.md
        - Adding new carousel banner: front-end/guides/add-banner.md
        - Adding new API spec: front-end/guides/new-spec-guide.md
        - MUI Basics: front-end/guides/mui-basics.md
        - Additional Resources: front-end/additional-resources.md
    - E-Commerce (CMC) Guides:
      - CMC Information: front-end/guides/cmc-info.md
      - HTML Guide: front-end/guides/e-marketing-html-guide.md
    - WordPress Site:
      - Project Information: front-end/wordpress-blocks-info.md
    # - Sharepoint Docs?:
    #   - Sharepoint Stuff: sharepoint.md
  - API Documentation:
    - B2B API Specs:
      - Account Statements: api/api-docs/account-statements.md
      - Backorder: api/api-docs/backorder.md
      - Create / Return Order:
        - Create Order: api/api-docs/create-order.md
        - Return Order: api/api-docs/return-order.md
      - GL Codes:
        - Enter New GL Code: api/api-docs/new-gl-code.md
        - View Code List: api/api-docs/gl-list.md
        - Code Summary: api/api-docs/gl-summary.md
        - GL Codes From Items: api/api-docs/gl-from-items.md
      - Invoice:
        - Invoice List: api/api-docs/invoice-list.md
        - Invoice Details: api/api-docs/invoice-details.md
      - Licensing:
        - Get License Info: api/api-docs/license-info.md
        - Validate License: api/api-docs/validate-license.md
      - Order List: api/api-docs/orders.md
      - Payment History: api/api-docs/payment-history.md
      - Get Pricing: api/api-docs/pricing.md
      - Purchase History: api/api-docs/purchase-history.md
      - Get Representative Info: api/api-docs/rep-info.md
      - Tax: api/api-docs/tax.md
      - VC: api/api-docs/vc.md
  - VM Setup: 
    - Toolkit Setup: vm-setup/toolkit-setup.md
    - VM / Toolkit Troubleshooting: vm-setup/toolkit-trouble-shoot.md
  - Git Guide: git-guide.md


extra_css:
  - stylesheets/custom-colors.css
  - stylesheets/custom-styling.css

copyright: MVS Developer Notes
extra:
  generator: false